services:
  - type: web
    name: physical-event-experience-backend
    runtime: node
    rootDir: backend
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: physical-event-experience-frontend
    runtime: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://physical-event-experience-backend.onrender.com/api
